-- 在 Supabase SQL Editor 中执行（若表已存在会跳过创建）
-- 字段：id, gid, title, content, version, release_date, url

create table if not exists public.dota2_updates (
  id bigint generated by default as identity primary key,
  gid text not null unique,
  title text not null,
  content text,
  version text,
  release_date timestamptz,
  url text
);

create index if not exists dota2_updates_version_release_idx
  on public.dota2_updates (version, release_date desc);

comment on table public.dota2_updates is 'Dota 2 补丁 / 公告同步（如 Steam ISteamNews）';

alter table public.dota2_updates enable row level security;

-- 匿名读（公开展示页）
drop policy if exists "dota2_updates_select_public" on public.dota2_updates;
create policy "dota2_updates_select_public"
  on public.dota2_updates for select
  using (true);

-- 开发同步按钮：匿名 upsert。若仅信任服务端写入，可删除以下两条并改用 service_role / Edge Function。
drop policy if exists "dota2_updates_insert_sync" on public.dota2_updates;
create policy "dota2_updates_insert_sync"
  on public.dota2_updates for insert
  with check (true);

drop policy if exists "dota2_updates_update_sync" on public.dota2_updates;
create policy "dota2_updates_update_sync"
  on public.dota2_updates for update
  using (true);
